import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { categories, products, settings } from "../lib/data";
const prisma = new PrismaClient();
async function main() {
  await prisma.product.updateMany({ where: { OR: [{ sku: { startsWith: "SJF-DEMO" } }, { sku: { startsWith: "NM-" } }] }, data: { isActive: false, isFeatured: false, isDemo: true, stock: 0 } });
  for (const category of categories) await prisma.category.upsert({ where: { slug: category.slug }, update: { name: category.name, nameUrdu: category.nameUrdu, nameEnglish: category.nameEnglish, description: category.description, isActive: true }, create: { id: category.id, name: category.name, nameUrdu: category.nameUrdu, nameEnglish: category.nameEnglish, slug: category.slug, description: category.description } });
  for (const product of products) { const category = await prisma.category.findUniqueOrThrow({ where: { id: product.category } }); await prisma.product.upsert({ where: { slug: product.slug }, update: { name: product.name, description: product.description, sku: product.sku, price: product.price, compareAtPrice: product.compareAtPrice, stock: product.stock, isFeatured: false, isActive: false, isDemo: true, categoryId: category.id }, create: { id: product.id, name: product.name, slug: product.slug, description: product.description, shortDescription: product.description.slice(0, 120), sku: product.sku, price: product.price, compareAtPrice: product.compareAtPrice, stock: product.stock, isFeatured: false, isActive: false, isDemo: true, categoryId: category.id, images: { create: { url: product.image, alt: product.name } } } }); }
  await prisma.businessSettings.upsert({ where: { id: "default" }, update: { businessName: settings.businessName, whatsappNumber: settings.whatsapp, contactNumbers: settings.contactNumbers, description: "Fresh fast food, bakery and sweets from SJ H.F.C.", currency: settings.currency, deliveryFee: settings.deliveryFee }, create: { id: "default", businessName: settings.businessName, whatsappNumber: settings.whatsapp, contactNumbers: settings.contactNumbers, description: "Fresh fast food, bakery and sweets from SJ H.F.C.", currency: settings.currency, deliveryFee: settings.deliveryFee, announcement: "Fresh food · Easy ordering · Direct to WhatsApp" } });
  const passwordHash = await bcrypt.hash(process.env.DEMO_ADMIN_PASSWORD || "Admin123!", 12); await prisma.user.upsert({ where: { email: "admin@sjhfc.demo" }, update: { passwordHash, role: "ADMIN" }, create: { name: "SJ H.F.C Admin", email: "admin@sjhfc.demo", passwordHash, role: "ADMIN" } });
}
main().finally(() => prisma.$disconnect());
