import { Category, Product } from "./types";
export const settings = { businessName:"SJ H.F.C", tagline:"Hot, fresh, made for your table.", currency:"Rs.", deliveryFee:250, whatsapp:process.env.WHATSAPP_BUSINESS_NUMBER || "923026924100", contactNumbers:["0302-6924100","0322-6993500","0314-5014999"] };
export const categories: Category[] = [
 {id:"shawarma",name:"شوارما",nameUrdu:"شوارما",nameEnglish:"Shawarma",slug:"shawarma",description:"Shawarma and wraps shown on the visiting card."},{id:"burger",name:"برگر",nameUrdu:"برگر",nameEnglish:"Burger",slug:"burger",description:"Burger items shown on the visiting card."},{id:"pizza",name:"پیزا",nameUrdu:"پیزا",nameEnglish:"Pizza",slug:"pizza",description:"Pizza items shown on the visiting card."},{id:"sandwich",name:"سینڈوچ",nameUrdu:"سینڈوچ",nameEnglish:"Sandwich",slug:"sandwich",description:"Sandwich items shown on the visiting card."},{id:"milkshake",name:"ملک شیک",nameUrdu:"ملک شیک",nameEnglish:"Milkshake",slug:"milkshake",description:"Milkshakes shown on the visiting card."},{id:"juice",name:"جوس",nameUrdu:"جوس",nameEnglish:"Juice",slug:"juice",description:"Juices shown on the visiting card."},{id:"fries",name:"فرائز",nameUrdu:"فرائز",nameEnglish:"Fries",slug:"fries",description:"Fries shown on the visiting card."}
 ];
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const products: Product[] = [
 {id:"p1",slug:"sample-menu-item-1",name:"Sample menu item 1",category:"burger",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1504671424907-c7f8f8a9b2f7"),featured:false,sku:"SJF-DEMO-001"},
 {id:"p2",slug:"sample-menu-item-2",name:"Sample menu item 2",category:"pizza",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1579751626657-72bc17010498"),featured:false,sku:"SJF-DEMO-002"},
 {id:"p3",slug:"sample-menu-item-3",name:"Sample menu item 3",category:"milkshake",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1544145945-f90425340c7e"),featured:false,sku:"SJF-DEMO-003"},
 {id:"p4",slug:"sample-menu-item-4",name:"Sample menu item 4",category:"sandwich",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1528735602780-2552fd46c7af"),sku:"SJF-DEMO-004"},
 {id:"p5",slug:"sample-menu-item-5",name:"Sample menu item 5",category:"juice",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1546173159-315724a31696"),sku:"SJF-DEMO-005"},
 {id:"p6",slug:"sample-menu-item-6",name:"Sample menu item 6",category:"fries",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1573080496219-bb080dd4f877"),sku:"SJF-DEMO-006"},
 {id:"p7",slug:"sample-menu-item-7",name:"Sample menu item 7",category:"shawarma",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1521305916504-4a1121188589"),sku:"SJF-DEMO-007"},
 {id:"p8",slug:"sample-menu-item-8",name:"Sample menu item 8",category:"burger",description:"INACTIVE SAMPLE ONLY. Replace with a verified item from the SJ H.F.C visiting card/menu.",price:0,stock:0,rating:0,reviews:0,image:img("photo-1568901346375-23c9450c58cd"),sku:"SJF-DEMO-008"}
];
export function getProduct(slug:string){return products.find(p=>p.slug===slug)}
export const money=(value:number)=>`${settings.currency} ${value.toLocaleString("en-PK")}`;
