import { Category, Product } from "./types";
export const settings = { businessName:"SJ H.F.C", tagline:"Hot, fresh, made for your table.", currency:"Rs.", deliveryFee:250, whatsapp:process.env.WHATSAPP_BUSINESS_NUMBER || "923026924100", contactNumbers:["0302-6924100","0322-6993500","0314-5014999"] };
export const categories: Category[] = [
 {id:"burgers",name:"Burgers",slug:"burgers",description:"Stacked, hot and satisfying."},{id:"pizza",name:"Pizza",slug:"pizza",description:"Freshly baked for sharing."},{id:"wraps",name:"Shawarma & Wraps",slug:"shawarma-wraps",description:"Wrapped with flavour."},{id:"fries",name:"Fries",slug:"fries",description:"Crisp sides for every order."},{id:"drinks",name:"Drinks",slug:"drinks",description:"Cold refreshment, sorted."},{id:"sweets",name:"Sweets & Bakery",slug:"sweets-bakery",description:"A little something sweet."}
];
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const products: Product[] = [
 {id:"p1",slug:"studio-wireless-headphones",name:"Studio Wireless Headphones",category:"burgers",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:8999,compareAtPrice:10999,stock:14,rating:4.9,reviews:86,image:img("photo-1505740420928-5e560c06d30e"),featured:true,sku:"SJF-DEMO-001"},
 {id:"p2",slug:"everyday-canvas-backpack",name:"Everyday Canvas Backpack",category:"pizza",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:3500,stock:23,rating:4.8,reviews:54,image:img("photo-1553062407-98eeb64c6a62"),featured:true,sku:"SJF-DEMO-002"},
 {id:"p3",slug:"ceramic-pour-over-set",name:"Ceramic Pour Over Set",category:"drinks",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:4200,stock:8,rating:4.7,reviews:31,image:img("photo-1495474472287-4d71bcdd2085"),featured:true,sku:"SJF-DEMO-003"},
 {id:"p4",slug:"linen-overshirt-sage",name:"Linen Overshirt / Sage",category:"wraps",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:5600,compareAtPrice:6800,stock:6,rating:4.8,reviews:22,image:img("photo-1596755389378-c31d21fd1273"),sku:"SJF-DEMO-004"},
 {id:"p5",slug:"minimal-desk-lamp",name:"Minimal Desk Lamp",category:"fries",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:4800,stock:12,rating:4.6,reviews:18,image:img("photo-1507473885765-e6ed057f782c"),sku:"SJF-DEMO-005"},
 {id:"p6",slug:"daily-face-cleanser",name:"Daily Face Cleanser",category:"sweets-bakery",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:1850,stock:40,rating:4.9,reviews:67,image:img("photo-1556228720-195a672e8a03"),sku:"SJF-DEMO-006"},
 {id:"p7",slug:"leather-card-wallet",name:"Leather Card Wallet",category:"burgers",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:2400,stock:19,rating:4.7,reviews:29,image:img("photo-1627123424574-724758594e93"),sku:"SJF-DEMO-007"},
 {id:"p8",slug:"portable-bluetooth-speaker",name:"Portable Bluetooth Speaker",category:"pizza",description:"Sample product for catalog setup. Replace with the verified SJ H.F.C menu before launch.",price:5200,compareAtPrice:5900,stock:10,rating:4.8,reviews:44,image:img("photo-1608043152269-423dbba4e7e1"),sku:"SJF-DEMO-008"}
];
export function getProduct(slug:string){return products.find(p=>p.slug===slug)}
export const money=(value:number)=>`${settings.currency} ${value.toLocaleString("en-PK")}`;
